### ISSUE TITLE
Object detection code

### ISSUE THREAD

**Issue by SaddamBInSyed** [grebtsew/Object-and-facial-detection-in-python#2]
Hi.

thanks for your code.

Is this repo contains object detection(car, truck, person) code as well ?

please advise

**Comment by grebtsew** [comment]
Hi @SaddamBInSyed !

This project mainly contain face detections using several different frameworks.
However I mention some tutorials on how to create custom object detection models in /Documentation & Learning.

If you want a simple working object detector with classification in Tensorflow such as Car and Person I would recommend checking this repo out:

https://github.com/jamesloyys/Real-Time-Object-Detection

It uses a slimmed version of the Tensorflow repository, I have forked this repo several times in the past.

Cheers,
@grebtsew

**Comment by SaddamBInSyed** [comment]
Thank you @grebtsew .

I will try and update you.
